import { WingetPackage, AppMode, PackageManagerType } from '../types';

/**
 * Sanitizes package IDs to prevent command injection attacks.
 * Only allows alphanumeric characters, dots, underscores, hyphens, and forward slashes.
 * This mirrors the validation in src-tauri/src/validation.rs
 */
const sanitizePackageId = (id: string): string => {
  // Remove any characters not allowed in package IDs
  const sanitized = id.replace(/[^A-Za-z0-9._\-/]/g, '');

  // Additional safety: reject if starts with dangerous characters
  if (sanitized.startsWith('.') || sanitized.startsWith('-') || sanitized.startsWith('/')) {
    return '';
  }

  // Limit length to prevent buffer overflow attacks
  return sanitized.substring(0, 256);
};

export const generateScript = (
  activePackages: WingetPackage[],
  mode: AppMode,
  packageManager: PackageManagerType
): string => {
  if (activePackages.length === 0) return '# No packages selected for script generation.';

  const pm = packageManager;
  const header = `# ${pm.charAt(0).toUpperCase() + pm.slice(1)} ${mode.charAt(0).toUpperCase() + mode.slice(1)} Script\n# Generated by WinGet Web`;

  if (pm === 'github') {
    if (mode === 'install') {
      return `${header}\n\n# Cloning repositories\n${activePackages
        .map((p) => {
          const safeId = sanitizePackageId(p.id);
          return safeId ? `git clone https://github.com/${safeId}.git` : '# Skipped invalid package ID';
        })
        .join('\n')}`;
    } else {
      return `${header}\n\n# GitHub mode mostly supports cloning (install). Upgrade/Uninstall requires manual Git operations.`;
    }
  }

  if (mode === 'uninstall') {
    if (pm === 'winget') {
      return `${header}\n\n$packages = @(\n${activePackages
        .map((p) => {
          const safeId = sanitizePackageId(p.id);
          return safeId ? `    "${safeId}"` : `    # Skipped invalid package ID: ${p.id}`;
        })
        .join(',\n')}\n)\n\nforeach ($id in $packages) {\n    winget uninstall --id $id -e\n}`;
    }
    const safeIds = activePackages.map((p) => sanitizePackageId(p.id)).filter((id) => id);
    if (pm === 'chocolatey') return `${header}\n\nchoco uninstall ${safeIds.join(' ')} -y`;
    if (pm === 'scoop') return `${header}\n\nscoop uninstall ${safeIds.join(' ')}`;
    if (pm === 'brew') return `${header}\n\nbrew uninstall ${safeIds.join(' ')}`;
    if (pm === 'apt') return `${header}\n\nsudo apt remove ${safeIds.join(' ')} -y`;
  }

  if (mode === 'upgrade') {
    const upgradable = activePackages.filter((p) => p.availableVersion);
    if (upgradable.length === 0) return `${header}\n\n# All selected packages are up to date.`;

    const safeIds = upgradable.map((p) => sanitizePackageId(p.id)).filter((id) => id);
    if (pm === 'winget')
      return `${header}\n\n${safeIds.map((id) => `winget upgrade --id ${id} -e --source winget`).join('\n')}`;
    if (pm === 'chocolatey') return `${header}\n\nchoco upgrade ${safeIds.join(' ')} -y`;
    if (pm === 'scoop') return `${header}\n\nscoop update ${safeIds.join(' ')}`;
    if (pm === 'brew') return `${header}\n\nbrew upgrade ${safeIds.join(' ')}`;
    if (pm === 'apt') return `${header}\n\nsudo apt upgrade ${safeIds.join(' ')} -y`;
  }

  if (mode === 'install') {
    const safeIds = activePackages.map((p) => sanitizePackageId(p.id)).filter((id) => id);
    if (pm === 'winget')
      return `${header}\n\n${safeIds.map((id) => `winget install --id ${id} -e --source winget`).join('\n')}`;
    if (pm === 'chocolatey') return `${header}\n\nchoco install ${safeIds.join(' ')} -y`;
    if (pm === 'scoop') return `${header}\n\nscoop install ${safeIds.join(' ')}`;
    if (pm === 'brew') return `${header}\n\nbrew install ${safeIds.join(' ')}`;
    if (pm === 'apt') return `${header}\n\nsudo apt install ${safeIds.join(' ')} -y`;
  }

  return `# Unknown mode or package manager`;
};
