
import { WingetPackage, AppMode, PackageManagerType } from '../types';

export const generateScript = (
  activePackages: WingetPackage[],
  mode: AppMode,
  packageManager: PackageManagerType
): string => {
  if (activePackages.length === 0) return '# No packages selected for script generation.';

  const pm = packageManager;
  const header = `# ${pm.charAt(0).toUpperCase() + pm.slice(1)} ${mode.charAt(0).toUpperCase() + mode.slice(1)} Script\n# Generated by WinGet Web`;

  if (pm === 'github') {
      if (mode === 'install') {
         return `${header}\n\n# Cloning repositories\n${activePackages.map(p => `git clone https://github.com/${p.id}.git`).join('\n')}`;
      } else {
         return `${header}\n\n# GitHub mode mostly supports cloning (install). Upgrade/Uninstall requires manual Git operations.`;
      }
  }

  if (mode === 'uninstall') {
      if (pm === 'winget') {
          return `${header}\n\n$packages = @(\n${activePackages.map(p => `    "${p.id}"`).join(',\n')}\n)\n\nforeach ($id in $packages) {\n    winget uninstall --id $id -e\n}`;
      }
      if (pm === 'chocolatey') return `${header}\n\nchoco uninstall ${activePackages.map(p => p.id).join(' ')} -y`;
      if (pm === 'scoop') return `${header}\n\nscoop uninstall ${activePackages.map(p => p.id).join(' ')}`;
      if (pm === 'brew') return `${header}\n\nbrew uninstall ${activePackages.map(p => p.id).join(' ')}`;
      if (pm === 'apt') return `${header}\n\nsudo apt remove ${activePackages.map(p => p.id).join(' ')} -y`;
  }

  if (mode === 'upgrade') {
      const upgradable = activePackages.filter(p => p.availableVersion);
      if (upgradable.length === 0) return `${header}\n\n# All selected packages are up to date.`;
      
      if (pm === 'winget') return `${header}\n\n${upgradable.map(p => `winget upgrade --id ${p.id} -e --source winget`).join('\n')}`;
      if (pm === 'chocolatey') return `${header}\n\nchoco upgrade ${upgradable.map(p => p.id).join(' ')} -y`;
      if (pm === 'scoop') return `${header}\n\nscoop update ${upgradable.map(p => p.id).join(' ')}`;
      if (pm === 'brew') return `${header}\n\nbrew upgrade ${upgradable.map(p => p.id).join(' ')}`;
      if (pm === 'apt') return `${header}\n\nsudo apt upgrade ${upgradable.map(p => p.id).join(' ')} -y`;
  }

  if (mode === 'install') {
      const ids = activePackages.map(p => p.id);
      if (pm === 'winget') return `${header}\n\n${ids.map(id => `winget install --id ${id} -e --source winget`).join('\n')}`;
      if (pm === 'chocolatey') return `${header}\n\nchoco install ${ids.join(' ')} -y`;
      if (pm === 'scoop') return `${header}\n\nscoop install ${ids.join(' ')}`;
      if (pm === 'brew') return `${header}\n\nbrew install ${ids.join(' ')}`;
      if (pm === 'apt') return `${header}\n\nsudo apt install ${ids.join(' ')} -y`;
  }

  return `# Unknown mode or package manager`;
};
